version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_PORT:$DB_DOCKER_PORT
    command: --init-file /data/application/userTable.sql
    volumes:
      - db:/var/lib/mysql
      - ./userTable.sql:/data/application/userTable.sql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - DB_PORT=$DB_DOCKER_PORT
      - PORT=$PORT
      - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
    stdin_open: true
    tty: true
volumes:
  db:
